repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: stable
    hooks:
      - id: ruff
        args: ["--fix", "--line-length=120"]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: ["--line-length=120"]
